update keystore location example
OpenLiberty/docs pull request #3828
Opened 2021-03-16 20:59 UTC by Rwalls1

2021-03-16 21:16 UTC, ManasiGandhi submitted a review, later dismissed

2021-03-16 22:05 UTC, dmuelle requested changes

2021-03-16 22:05 UTC, dmuelle commented on modules/reference/pages/feature/mpJwt/examples.adoc
> +<keyStore id="defaultTrustStore" location="MyKeyStoreFile.jks" type="JKS" password="changeit" />
since .jks is an older file format, we should use .p12, which is liberty default. So `location="MyKeyStoreFile.p12"`

2021-03-17 01:00 UTC, dmuelle approved these changes

2021-03-17 11:47 UTC, merged