4534 AES Encryption Update based on skill case
OpenLiberty/docs pull request #4560
Opened 2021-08-18 11:59 UTC by ramkumar-k-9286

AES Encryption Update based on skill case:

2 docs updated:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/password-encryption.html
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/reference/command/securityUtility-encode.html

#4534

2021-08-18 14:58 UTC, dmuelle reviewed
two minor comments- disregard the other file changes in this PR- they are ok

2021-08-18 14:58 UTC, dmuelle commented on modules/reference/pages/command/securityUtility-encode.adoc
> +If this option isn't specified, a default encoding type of `xor` is used. Currently, aes type uses AES 128 encryption.
Currently, aes type uses AES 128 encryption.

---->

Currently, the `aes` type uses AES-128 encryption.

2021-08-18 14:58 UTC, dmuelle commented on modules/ROOT/pages/password-encryption.adoc
> +When you use this option for protecting passwords in the Open Liberty configuration, understand the limits to the protection that AES encryption provides. Currently, Open Liberty supports AES 128 enc
AES-128

2021-08-19 10:15 UTC, ramkumar-k-9286 commented
@dmuelle 
Correction done. Updated AES 128 to AES-128.

2021-08-19 13:18 UTC, dmuelle commented on modules/reference/pages/command/securityUtility-encode.adoc
> +If this option isn't specified, a default encoding type of `xor` is used. Currently, aes type uses AES-128 encryption.
Currently, aes type uses AES-128 encryption
---->
 Currently, the `aes` type uses AES-128 encryption

2021-08-19 13:19 UTC, dmuelle requested changes
monospace `aes` type (lowercase instance only)

2021-08-19 18:24 UTC, dmuelle approved these changes
LGTM

2021-08-19 18:25 UTC, merged