4687-springbootutility-thin-doc-update
OpenLiberty/docs pull request #4792
Opened 2021-10-14 19:17 UTC by ramkumar-k-9286

springbootutility-thin-doc-update

#4687

2021-10-14 19:19 UTC, dmuelle requested changes

2021-10-14 19:19 UTC, dmuelle commented on modules/reference/pages/command/springbootUtility-thin.adoc
> +
add a title for the options table as well:

 .Options for the springBootUtility thin command

2021-10-18 12:14 UTC, ramkumar-k-9286 commented on modules/reference/pages/command/springbootUtility-thin.adoc
> +
Correction done. 

Added:
.Options for the springBootUtility thin command

2021-10-18 12:53 UTC, dmuelle approved these changes
LGTM, thanks

2021-10-18 18:42 UTC, merged