Update and clarify JWT docs
OpenLiberty/docs pull request #6963
Opened 2023-10-11 16:57 UTC by ayoho

Add some sections on JWK usage in the JWT builder and consumer doc.

For https://github.com/OpenLiberty/open-liberty/issues/26453

2023-10-11 17:17 UTC, jimmy1wu approved these changes

2023-10-11 17:19 UTC, jimmy1wu commented on modules/reference/pages/feature/jwt/examples.adoc
> +Dynamically generated JWKs are useful for server administrators that do not want to be concerned with setting up a keystore and signing key for the JWT builder. Server admins need only set the `jwkEn
```suggestion
Dynamically generated JWKs are useful for server administrators that do not want to be concerned with setting up a keystore and signing key for the JWT builder. Server administrators only need to set the `jwkEnabled` attribute to `true`, and Liberty will handle creation and maintenance of the key. Note that when `jwkEnabled` is set to `true`, the `keyStoreRef` and `keyAlias` attributes will be ignored.
```

2023-10-11 17:20 UTC, jimmy1wu commented on modules/reference/pages/feature/jwt/examples.adoc
> +The `jwkEnabled` attribute in the `jwtConsumer` element must be set to `true`, and the `jwkEndpointUrl` attribute must be set to a URI that provides the JWKS document containing the public keys to us
```suggestion
The `jwkEnabled` attribute in the `jwtConsumer` element must be set to `true`, and the `jwkEndpointUrl` attribute must be set to a URI that provides the JWKS document containing the public keys to use to verify the signatures of the tokens received by this JWT consumer.
```

2023-10-11 17:56 UTC, dmuelle commented
opened #6964 to track on docs side

2023-10-11 18:09 UTC, dmuelle requested changes
Ho @ayoho - thanks for opening this. Some general comments before I review/edit

The Examples sections on the feature pages are intended to be for concise configuration examples that demonstrate common tasks. The info in this PR seems more like conceptual information to support JWT Builder. Is it possible to revise this information to be focused on config examples that demonstrate the main ideas? It might also make the sections more concise if we show rather than tell the config details, and just provide context in the example descriptions.

Also, the OL website does not really recognize h4 or h5 headings. But if the info was broken up into examples, we could just use h3 for each example.

I'm happy to help revise the info you have here. If the information is better presented as conceptual topic, we can create a new topic and link it form this page. Let me know what you think. Thanks!

2023-10-11 19:25 UTC, ayoho commented
Hi, @dmuelle. I'd agree that the content is primarily conceptual. Perhaps revamping the https://openliberty.io/docs/latest/single-sign-on.html#_json_web_token_jwt section and maybe even having a standalone page under the Security section for JSON Web Tokens would be a better place to have this information. I can create a new `modules/ROOT/pages/json-web-token.adoc` page for this content, but if we go that route I might need some more help with how to get it correctly hooked into the site. Looks like I'd update `modules/ROOT/nav.adoc` to add a link to the new page where I want under the Security section. Anything else?

2023-10-11 19:32 UTC, dmuelle commented
that's all you need to do- BUT - when you update the nav, make that change in the `draft-nav` branch and create a separate PR to `draft`.  We have dedicated branches just for updating the draft and staging nav files to avoid merge conflicts since the nav is different on draft vs staging/vNext.

2023-10-11 19:32 UTC, dmuelle commented
https://github.com/OpenLiberty/docs#editing-the-docs-navigation

2023-10-12 19:21 UTC, ayoho commented
@dmuelle I moved all my new content into a separate json-web-token.adoc page. I'll open a separate PR for the nav changes.

2023-10-12 21:00 UTC, dmuelle approved these changes
LGTM

2023-10-12 21:00 UTC, merged

2023-10-12 21:00 UTC, dmuelle commented
I'm merging this to draft and will review further and make edits for IBM style etc in a new PR